# Generated by Django 6.0.4 on 2026-05-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='investment_industries',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_companies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
